name: Twitter Bot Workflow

on:
  push:
    branches:
      - main  # Adjust this if your default branch is named differently
  workflow_dispatch:  # Allows manual triggering

jobs:
  run_twitter_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests-oauthlib notdiamond requests

      - name: Run Twitter Bot
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ND_API_KEY: ${{ secrets.ND_API_KEY }}  # Ensure this matches your secret
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # If needed
        run: |
          python app.py 
